apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 3  # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: murlipatel1/node-app:latest
          ports:
            - containerPort: 3000
